<?php return array (
  'version' => '1.3.1',
  'install_default_template' => 'cotiqu',
  'install_default_template_content' => 1,
  'compile_assets' => 1,
  'disable_model_cache' => 0,
  'admin_url' => 'admin',
  'site_lang' => 'en_US',
  'has_admin' => 1,
  'is_installed' => 1,
  'updated_at' => '2022-11-09 07:31:59',
  'force_https' => 0,
  'update_channel' => 'stable',
  'developer_mode' => 1,
);